// frontend-vue/src/App.vue
<template>
  <div>
    <h2>Login / Register Vue</h2>
    <input v-model="username" placeholder="Username" />
    <input v-model="password" type="password" placeholder="Password" />
    <button @click="register">Register</button>
    <button @click="login">Login</button>
    <p>{{ message }}</p>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      username: '',
      password: '',
      message: ''
    };
  },
  methods: {
    async register() {
      try {
        const res = await axios.post('http://localhost:3001/api/register', {
          username: this.username,
          password: this.password
        });
        this.message = res.data.message;
      } catch (e) {
        this.message = e.response?.data?.error || 'Erreur';
      }
    },
    async login() {
      try {
        const res = await axios.post('http://localhost:3001/api/login', {
          username: this.username,
          password: this.password
        });
        this.message = res.data.message;
      } catch (e) {
        this.message = e.response?.data?.error || 'Erreur';
      }
    }
  }
};
</script>

// frontend-react/src/App.js
import React, { useState } from "react";
import axios from "axios";

export default function App() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");

  const register = async () => {
    try {
      const res = await axios.post("http://localhost:3001/api/register", { username, password });
      setMessage(res.data.message);
    } catch (e) {
      setMessage(e.response?.data?.error || "Erreur");
    }
  };

  const login = async () => {
    try {
      const res = await axios.post("http://localhost:3001/api/login", { username, password });
      setMessage(res.data.message);
    } catch (e) {
      setMessage(e.response?.data?.error || "Erreur");
    }
  };

  return (
    <div>
      <h2>Login / Register</h2>
      <input placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} />
      <input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} />
      <button onClick={register}>Register</button>
      <button onClick={login}>Login</button>
      <p>{message}</p>
    </div>
  );
}
